services:
  api_consultanit_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      - NODE_ENV=development
      - DEBUG=true
    depends_on:
      - pgamin

  consultaNIT_db:
    image: postgres:17
    container_name: db_dev_container
    restart: always
    ports:
      - "${DB_PORT}:5432" 
    environment:
      POSTGRES_DB: ${DB_USER_EMAIL}
      POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PORT}
    volumes:
      - db_dev:/var/lib/postgresql/data
  
  pgamin:
    image: dpage/pgadmin4
    container_name: ${DB_NAME}     
    restart: always
    ports:
      - "${PGADMIN_LISTEN_PORT_DEV}:81" 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USER_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      PGADMIN_LISTEN_PORT: 81
    volumes:
      - db_dev:/var/lib/pgadmin
    depends_on:
      - consultaNIT_db

volumes:
  db_dev:
