services: 
  api_consultanit_prod:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "${SERVER_PORT}:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - dpage_prod
    
  consultaNIT_db_prod:
      image: postgres:17
      container_name: db_prod
      restart: always
      ports:
        - "${DB_PORT}:5432" 
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - db_dev_data:/var/lib/postgresql/data
      

  dpage_prod:
    image: dpage/pgadmin4
    container_name: db_consultanit_prod
    restart: always
    ports:
      - "${PGADMIN_LISTEN_PORT_PROD}:80" 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL_PROD}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD_PROD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - db_dev_data:/var/lib/pgadmin
    depends_on:
      - consultaNIT_db_prod

volumes:
  db_dev_data: 



    
