services: 
  api_consultanit_prod:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "${SERVER_PORT}:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api_db
    
  api_db:
    image: postgres:17
    ports: 
      - "{$DB_PORT_PROD}:5462"
    environment:
      POSTGRES_USER: ${DB_USER_PROD}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PROD}
      POSTGRES_DB: ${DB_NAME_PROD}
    volumes:
      - db_data:/var/lib/postgresql/data
    
volumes:
  db_data: 


    
